name: Device Lens

default-view: Laptops

datasets:
  Laptops:
    path: data/Laptops-RawData.csv
  
  Desktops:
    path: data/Desktops-RawData.csv

  Demo:
    path: data/Laptops/Demos-RawData.csv

  Dev:
    path: data/Laptops/Dev-RawData.csv

  Travel Dev:
    path: data/Laptops/TravelDev-RawData.csv

  Business:
    path: data/Laptops/Business-RawData.csv

  Tablet:
    path: data/Laptops/Tablet-RawData.csv

views:
  Laptops:
    dataset: Laptops
    desc: |
      Laptop machines bechmarked using the Esri ArcGIS Pro **Performance Assessment Tool**, **CineBench** for GPU, Multi/Single-Core 3D Image Generation, and **Blender** for Sampling Rates.
    render-table:
      columns:
        Model:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category20b

        PAT Completion (mins):
          plot:
            ticks:
              scale: linear
        
        Multi-Core (Points):
          plot:
            bars:
              scale: linear

        Single-Core (Points):
          plot:
            bars:
              scale: linear
  
  Desktops:
    dataset: Desktops
    desc: |
     Desktop machines benchmarked using the Esri ArcGIS Pro **Performance Assessment Tool**, **CineBench** for GPU, Multi/Single-Core 3D Image Generation, and **Blender** for Sampling Rates.
    render-table:
      columns:
        Model:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category20b
        PAT Completion (Mins):
          plot:
            ticks:
              scale: linear

        GPU Scores (Points):
          plot:
            bars:
              scale: linear

        Multi-Core (Points):
          plot:
            bars:
              scale: linear

        Single-Core (Points):
          plot:
            bars:
              scale: linear
